/**
 * post.js
 * Single post page: read ?slug= from the URL, fetch the post
 * from Supabase, inject SEO metadata, and render the content.
 *
 * Security note:
 *  The post body is stored as trusted HTML generated by the n8n workflow.
 *  We run it through a lightweight DOMParser sanitisation pass before
 *  inserting it into the DOM to strip script tags and event handlers.
 *  For production, consider adding DOMPurify for a more robust defence.
 */

import { fetchPostBySlug, formatDate, FALLBACK_IMAGE } from './supabase.js';

// ── DOM references ────────────────────────────────────────────────────────
const skeletonEl  = document.getElementById('post-skeleton');
const contentEl   = document.getElementById('post-content');
const errorEl     = document.getElementById('error-state');
const errorMsgEl  = document.getElementById('error-message');

// Post elements
const titleEl     = document.getElementById('post-title');
const dateEl      = document.getElementById('post-date');
const readTimeEl  = document.getElementById('post-read-time');
const imageEl     = document.getElementById('post-image');
const bodyEl      = document.getElementById('post-body');

// ── Helpers ───────────────────────────────────────────────────────────────

/**
 * Return the ?slug= parameter from the current URL.
 * @returns {string|null}
 */
function getSlugFromUrl() {
  const params = new URLSearchParams(window.location.search);
  return params.get('slug');
}

/**
 * Estimate reading time from raw text content.
 * @param {string} html
 * @returns {string} e.g. "4 min read"
 */
function estimateReadTime(html) {
  const text  = html.replace(/<[^>]*>/g, ' ');
  const words = text.trim().split(/\s+/).length;
  const mins  = Math.max(1, Math.round(words / 220));
  return `${mins} min read`;
}

/**
 * Minimal HTML sanitisation — removes <script>, <iframe>, and
 * inline event handler attributes before injecting into the DOM.
 * @param {string} html
 * @returns {string} sanitised HTML string
 */
function sanitiseHtml(html) {
  const parser = new DOMParser();
  const doc    = parser.parseFromString(html, 'text/html');

  // Remove dangerous elements
  doc.querySelectorAll('script, iframe, object, embed, form').forEach(el => el.remove());

  // Remove inline event handlers (onclick, onload, onerror, etc.)
  doc.querySelectorAll('*').forEach(el => {
    [...el.attributes].forEach(attr => {
      if (attr.name.startsWith('on')) el.removeAttribute(attr.name);
    });
  });

  return doc.body.innerHTML;
}

// ── SEO injection ─────────────────────────────────────────────────────────

/**
 * Dynamically update all SEO-related meta tags with post data.
 * @param {Object} post
 */
function injectSeoMeta(post) {
  const siteBase = window.location.origin;
  const postUrl  = `${siteBase}/post.html?slug=${encodeURIComponent(post.slug)}`;
  const ogImage  = post.featured_image || FALLBACK_IMAGE;
  const metaDesc = post.seo_description || post.excerpt || '';
  const metaTitle = post.seo_title || post.title || 'The Brief';

  // <title>
  document.title = `${metaTitle} — The Brief`;

  // Helper to set meta content by name or property
  const setMeta = (selector, value) => {
    const el = document.querySelector(selector);
    if (el) el.setAttribute('content', value);
  };

  setMeta('meta[name="description"]',        metaDesc);
  setMeta('meta[property="og:title"]',       metaTitle);
  setMeta('meta[property="og:description"]', metaDesc);
  setMeta('meta[property="og:image"]',       ogImage);
  setMeta('meta[property="og:url"]',         postUrl);
  setMeta('meta[name="twitter:title"]',      metaTitle);
  setMeta('meta[name="twitter:description"]',metaDesc);
  setMeta('meta[name="twitter:image"]',      ogImage);

  // Canonical
  const canonical = document.getElementById('canonical-link');
  if (canonical) canonical.setAttribute('href', postUrl);
}

// ── Render ────────────────────────────────────────────────────────────────

/**
 * Populate all post DOM elements with fetched data.
 * @param {Object} post
 */
function renderPost(post) {
  const formattedDate = formatDate(post.created_at);

  // Meta row
  dateEl.textContent  = formattedDate;
  dateEl.setAttribute('datetime', post.created_at);
  readTimeEl.textContent = estimateReadTime(post.content || '');

  // Title
  titleEl.textContent = post.title;

  // Featured image
  const imgSrc  = post.featured_image || FALLBACK_IMAGE;
  imageEl.src   = imgSrc;
  imageEl.alt   = post.title;
  imageEl.onerror = () => { imageEl.src = FALLBACK_IMAGE; };

  // Body — sanitised HTML from Supabase (produced by n8n workflow)
  bodyEl.innerHTML = sanitiseHtml(post.content || '<p>No content available.</p>');

  // Inject SEO
  injectSeoMeta(post);

  // Reveal post, hide skeleton
  skeletonEl.hidden = true;
  contentEl.hidden  = false;
}

// ── Error display ─────────────────────────────────────────────────────────

function showError(message) {
  skeletonEl.hidden = true;
  if (errorMsgEl) errorMsgEl.textContent = message;
  errorEl.hidden = false;
}

// ── Initialise ────────────────────────────────────────────────────────────

async function init() {
  const slug = getSlugFromUrl();

  if (!slug) {
    showError('No article slug was provided. Please navigate from the homepage.');
    return;
  }

  try {
    const post = await fetchPostBySlug(decodeURIComponent(slug));
    renderPost(post);
  } catch (err) {
    console.error('[Blog] Failed to load post:', err);

    // Supabase returns a PGRST116 code when no rows are found
    if (err?.code === 'PGRST116' || err?.message?.includes('no rows')) {
      showError('This article doesn't exist or has been unpublished.');
    } else {
      showError('Could not load this article. Please try again later.');
    }
  }
}

// ── Boot ──────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', init);
